stages:
  - test
#  - deploy
#  - production_test

default:
  image: test

lint:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run lint

units:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run test