name: test backend app workflow
on: push
jobs:
  check_server_available:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
#      - name: Run server
#        run: npm run start