name: Frontend Workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello GH Actions
      - name: Print to console 2
        run: |
          echo Hello GH Actions 1
          echo Hello GH Actions 1