name: test frontend app workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm run test