name: linter and tests
on: push
jobs:
  js_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  js_test:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run js test
        run: npm run test